apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - secret-template.yaml
  - configmap.yaml
  - ingress.yaml

commonLabels:
  managed-by: github-actions
  app.kubernetes.io/name: bisa-backend
