-- AlterTable
ALTER TABLE `negotiations` MODIFY `status` ENUM('OPEN_NEGOTIATION', 'OFFER_SUBMITTED', 'OFFER_ACCEPTED', 'OFFER_REJECTED', 'EXPIRED', 'LOCKED', 'CANCELLED') NOT NULL DEFAULT 'OPEN_NEGOTIATION';
