UPDATE `rfqs` SET `biomassa_type` = 'OTHER' WHERE `biomassa_type` NOT IN ('BIOCHAR', 'SEKAM_PADI', 'TONGKOL_JAGUNG', 'TEMPURUNG_KELAPA', 'WOOD_CHIP', 'OTHER');

ALTER TABLE `rfqs` MODIFY COLUMN `biomassa_type` ENUM('BIOCHAR', 'SEKAM_PADI', 'TONGKOL_JAGUNG', 'TEMPURUNG_KELAPA', 'WOOD_CHIP', 'OTHER') NULL;
